# Custom values for the Bitnami PostgreSQL Helm chart
# Updated for chart 16.x
# Documentation: https://github.com/bitnami/charts/tree/main/bitnami/postgresql

global:
  security:
    allowInsecureImages: true

image:
  registry: public.ecr.aws
  repository: bitnami/postgresql

auth:
  database: "metastore"
  username: "postgres"
  existingSecret: "postgres-secret"

# We only need a single, primary instance. No read replicas.
primary:
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Disable read replicas as they are not needed for this use case
readReplicas:
  enabled: false

# Disable metrics exporter to save resources
metrics:
  enabled: false

