apiVersion: v1
kind: Service
metadata:
  name: identity-worker
  labels:
    app: enginedge
    component: identity-worker
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
    name: http
  selector:
    app: enginedge
    component: identity-worker

