apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: worker-node-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: enginedge
      component: worker-node
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: enginedge
          component: kafka
    ports:
    - protocol: TCP
      port: 9092
  - to:
    - podSelector:
        matchLabels:
          app: enginedge
          component: main-node
    ports:
    - protocol: TCP
      port: 3000
