apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
  labels:
    app: enginedge
    component: {{ .Values.component }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    name: http
  selector:
    app: enginedge
    component: {{ .Values.component }}
