apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apps/main-node.yaml
# - apps/worker-node.yaml
- apps/interview-worker.yaml
- apps/scheduling-worker.yaml
- apps/scheduling-model.yaml
- apps/resume-worker.yaml
- apps/spacy-service.yaml
- apps/mongodb.yaml
# Datalake Components
- apps/hive-metastore.yml
- apps/spark.yml
- apps/trino.yml
- config/main-node-config.yaml
# - config/worker-node-config.yaml
- config/interview-worker-config.yaml
- config/scheduling-model-config.yaml
- config/resume-worker-config.yaml
- config/spacy-service-config.yaml
- rbac/main-node-observability-rbac.yaml

patches:
- path: host-docker-internal.yaml

namespace: default 