apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datalake-minio
  namespace: enginedge
  labels:
    app: enginedge
    component: datalake
    service: minio
spec:
  selector:
    matchLabels:
      app: enginedge
      component: datalake
      service: minio
  endpoints:
    - port: api
      path: /minio/v2/metrics/cluster
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
