kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: core
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cgroup-driver: cgroupfs
  - |
    kind: KubeletConfiguration
    cgroupDriver: cgroupfs
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
