apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-worker-config
  namespace: default
data:
  # General
  NODE_ENV: "production"
  PORT: "3002"
  NODE_TYPE: "interview"
  USER_ID: "system"

  # Service URLs
  COMMANDER_NODE_URL: "http://main-node:3000"

  # Kafka Configuration
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_SASL_MECHANISM: "plain"
  KAFKA_SASL_USERNAME: "user1"
