apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: enginedge
    component: api-gateway
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort }}
    name: http
  selector:
    app: enginedge
    component: api-gateway

