apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: default
data:
  KAFKA_BROKERS: "kafka-0.kafka.default.svc.cluster.local:9092,kafka-1.kafka.default.svc.cluster.local:9092"

